apiVersion: v1
kind: ConfigMap
metadata:
  name: doc-chat-config
  namespace: doc-chat
data:
  application.yaml: |
    server:
      port: 8080

    logging:
      level:
        org:
          atmosphere: warn

    management:
      endpoints:
        web:
          exposure:
            include: prometheus, info, health, metrics

    spring:
      mustache:
        check-template-location: false
      jpa:
        defer-datasource-initialization: true
      sql:
        init:
          mode: always
      profiles:
        active: dev
      data:
        mongodb:
          uri: mongodb://admin:password123@mongodb-service:27017/docs?authSource=admin
          database: docs
          collection: documents
          index-name: default
      autoconfigure:
        exclude:
          - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
          - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

    vaadin:
      launch-browser: false
      allowed-packages:
        - com.vaadin
        - org.vaadin
        - dev.hilla
        - com.vaadin.demo
      logging:
        level:
          dev:
            langchain4j: DEBUG
            ai4j:
              openai4j: DEBUG

    ai:
      docs:
        location: /app/documents
        langchain4j:
          openAi:
            apiKey: ollama
            baseUrl: http://ollama-service:11434
            modelName: llama3.2
            embeddingModelName: nomic-embed-text
