# Alternative Secret configuration for using OpenAI API instead of Ollama
# To use this configuration:
# 1. Replace YOUR_OPENAI_API_KEY with your actual API key
# 2. Base64 encode it: echo -n "your-api-key" | base64
# 3. Replace the OPENAI_API_KEY value below
# 4. Apply this instead of the default secret: kubectl apply -f k8s/openai-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: doc-chat-secret
  namespace: doc-chat
type: Opaque
data:
  # Base64 encoded values for OpenAI configuration
  # mongodb://admin:password123@mongodb-service:27017/docs?authSource=admin
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9kb2NzP2F1dGhTb3VyY2U9YWRtaW4=
  # /app/documents
  AI_DOCS_LOCATION: L2FwcC9kb2N1bWVudHM=
  # https://api.openai.com/v1
  OPENAI_API_BASE_URL: aHR0cHM6Ly9hcGkub3BlbmFpLmNvbS92MQ==
  # gpt-3.5-turbo
  OPENAI_API_MODEL_NAME: Z3B0LTMuNS10dXJibw==
  # text-embedding-ada-002
  OPENAI_API_EMBEDDING_MODEL_NAME: dGV4dC1lbWJlZGRpbmctYWRhLTAwMg==
  # REPLACE THIS WITH YOUR BASE64 ENCODED OPENAI API KEY
  OPENAI_API_KEY: WU9VUl9PUEVOQUFQSV9LRVlfSEVSRQ==
