apiVersion: v1
kind: PersistentVolume
metadata:
  name: qdrant-pv-host
  labels:
    type: local
    app: qdrant
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/storage/qdrant  # Mounted from macOS
    type: DirectoryOrCreate