apiVersion: v1
kind: Secret
metadata:
  name: doc-chat-secret
  namespace: doc-chat
type: Opaque
data:
  # MongoDB Atlas connection string (replace with your actual connection string)
  # Format: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/<database>?retryWrites=true&w=majority
  # This is a placeholder - you need to replace with your actual Atlas connection string
  MONGODB_URI: bW9uZ29kYitzcnY6Ly88dXNlcm5hbWU+OjxwYXNzd29yZD5AY2x1c3Rlci5tb25nb2RiLm5ldC9kb2NzP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQ==
  
  # /app/documents
  AI_DOCS_LOCATION: L2FwcC9kb2N1bWVudHM=
  
  # http://ollama-service:11434
  OPENAI_API_BASE_URL: aHR0cDovL29sbGFtYS1zZXJ2aWNlOjExNDM0
  
  # llama3.2
  OPENAI_API_MODEL_NAME: bGxhbWEzLjI=
  
  # nomic-embed-text
  OPENAI_API_EMBEDDING_MODEL_NAME: bm9taWMtZW1iZWQtdGV4dA==