apiVersion: v1
kind: Secret
metadata:
  name: doc-chat-secret
  namespace: doc-chat
type: Opaque
data:
  # Base64 encoded values
  # mongodb://admin:password123@mongodb-service:27017/docs?authSource=admin
  MONGODB_URI: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9kb2NzP2F1dGhTb3VyY2U9YWRtaW4=
  # /app/documents
  AI_DOCS_LOCATION: L2FwcC9kb2N1bWVudHM=
  # http://ollama-service:11434
  OPENAI_API_BASE_URL: aHR0cDovL29sbGFtYS1zZXJ2aWNlOjExNDM0
  # llama3.2
  OPENAI_API_MODEL_NAME: bGxhbWEzLjI=
  # nomic-embed-text
  OPENAI_API_EMBEDDING_MODEL_NAME: bm9taWMtZW1iZWQtdGV4dA==
